title:              Angular GraphQL Book
email:              email@angulargraphqlbook.com
description:        "Full Stack Development with Angular and GraphQL: Learn to build scalable monorepo and a complete Angular app using Apollo, Lerna, and GraphQL"
author:             Ahmed Bouchefra
baseurl:            "/"
url:                "http://angulargraphqlbook.com"

# Social Profiles
twitter_username:   techiediaries
github_username:    techiediaries
facebook_username:  techiediaries9
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
permalink:   /:categories/:title/
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
